In [1]:
import os
from pathlib import Path

# Move working directory from notebooks/ → project root
os.chdir(Path.cwd().parent)

print("Working directory:", os.getcwd())

Working directory: /Users/maithreyeeiyengar/Library/Mobile Documents/com~apple~CloudDocs/Gen AI Lab/Final Project/GenAI_FinalProject

In [2]:
raw_dir = Path("data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)
raw_dir.resolve()

PosixPath('/Users/maithreyeeiyengar/Library/Mobile Documents/com~apple~CloudDocs/Gen AI Lab/Final Project/GenAI_FinalProject/data/raw')

In [4]:
from dotenv import load_dotenv
from openai import OpenAI
import os

# load .env for OPENAI_API_KEY, HF_TOKEN, etc.
load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
print("Key prefix:", api_key[:10], "********")

client = OpenAI()  # we'll use this later

Key prefix: sk-proj-Sw ********

In [5]:
import pandas as pd
from pathlib import Path

Path("data/metadata").mkdir(parents=True, exist_ok=True)

products = [
    {
        "Product_ID": "P1",
        "Product_Name": "Sony WH-1000XM5 Wireless Noise-Canceling Headphones",
        "Category": "Electronics",
        "Item": "Headphones",
        "Marketplace": "Amazon",
        "URL": "amazon.com/Sony-WH-1000XM5-Headphones-Hands-Free-WH1000XM5/dp/B0BXYCS74H/ref=sr_1_1?dib=eyJ2IjoiMSJ9.AiQTnHr7j97_VMmMJ1xxyGyKe07EpHd2QvBVXU5Z1GKclV0Tb5kn1I4Ikq_2QC6u0KNbmyYIuQkqbP6LPkat7H6L3F7xY9-2BcJ4ppl8x3glkuuOtEC8GtLRGwYalHz1OVlfLiGa_3M4VRPb-AIRhCKh4lFwJCyrVpYiJSO-6I6UgJrasVtXNSpVOQik4gc--iPerSqH6P4yY-873izKg82YyJRCz2XiBV5jnLrnjYA.cHHufX3MXotdMbF8hpAZEWDOlArCT_iaXdZNxvxCD5g&dib_tag=se&hvadid=676179671513&hvdev=c&hvexpln=0&hvlocphy=9194732&hvnetw=g&hvocijid=9596794597661192146--&hvqmt=e&hvrand=9596794597661192146&hvtargid=kwd-2003882119095&hydadcr=15454_13495259&keywords=headset+sony+wh-1000xm5&mcid=a726d785e2f7327cbbee957f9ae1024f&qid=1764194439&sr=8-1"
    },
    {
        "Product_ID": "P2",
        "Product_Name": "Ninja AF101 4-Quart Air Fryer",
        "Category": "Kitchen Appliances",
        "Item": "Air Fryer",
        "Marketplace": "Amazon",
        "URL": "https://www.amazon.com/Ninja-Capacity-Dehydrate-Technology-AF181/dp/B0CS3V8M9H/ref=sr_1_1?dib=eyJ2IjoiMSJ9.ye0FK2RegR6ZKUpP9caYUJ0Z7k6F7RN2sptRVDNtrbI-ENKqWAJycWzmIEAVzCh7JFQLnNoKEj_7w6lEL9R5piI5XLSt7cqIStnKcCE-JD5cRYnwqDlvZmOVxsaFHR4t2dPAfe9HSTphTLmVDc6reQz9z_OEu_brCHWqvClLI7syc2phG8VcY93mQbMJX802KD8sMzNPl1pp9MHbODNZJ7HZV5HcGRsm1ryy57Xd7hM.7HOStVqgMkge0h8Eyz93zn7zN7PtVNDbh4ZnbipGYcs&dib_tag=se&hvadid=410018111006&hvdev=c&hvexpln=0&hvlocphy=9194732&hvnetw=g&hvocijid=12120195360623948812--&hvqmt=e&hvrand=12120195360623948812&hvtargid=kwd-1909413989643&hydadcr=20213_11121127&keywords=ninja%2Baf101%2B4%2Bquart%2Bair%2Bfryer&mcid=24c3ba891dc53faf9500ee9984694985&qid=1764194465&sr=8-1&th=1"
    },
    {
        "Product_ID": "P3",
        "Product_Name": "CeraVe Hydrating Facial Cleanser, 16 oz",
        "Category": "Beauty",
        "Item": "Facial Cleanser",
        "Marketplace": "Amazon",
        "URL": "https://www.amazon.com/CeraVe-Hydrating-Facial-Cleanser-Washing/dp/B00D7BZJ3C/ref=sr_1_1?dib=eyJ2IjoiMSJ9.1YJj7EcWpOPtCF4FrREf8kaDEx1q5jglKwzUbJ6W_f_WSX9XopJM4qhZNJHpAwzXJo5_SqSfj8HMdsJJj2wBeLwxuEr49D-8zxtrSKr18RyrWWdpRrwHRP6DlgVeKcx84m7E3IVZJNL5dwyLer6rsp4cX0iOy4tLPC-Lj3HnSi_Vo8gAH4I-ontPbUr2ibaeJoUAl8qS1hlwDrnkbiOdRcFvt_TreYkihSLXpj89tvmtaS66TkDAO5o9f96T2n5vXoFlDB0bHR749rWlCIb85nllxzV6-xLQtMuFrAPGZ9I.i7CXl_ENXNqiJ9CdM_Eh21vWwIP6wBDP5zohKfPtpfE&dib_tag=se&hvadid=410031880743&hvdev=c&hvexpln=0&hvlocphy=9194732&hvnetw=g&hvocijid=16897500214369218395--&hvqmt=e&hvrand=16897500214369218395&hvtargid=kwd-938153012067&hydadcr=27503_11866331&keywords=cerave%2Bhydrating%2Bcleanser%2Bfor%2Bface&mcid=6308e5a163fc30a2af39e7516286a27f&qid=1764194487&sr=8-1&th=1"
    },
]

product_df = pd.DataFrame(products)
product_df.to_csv("data/metadata/product_list.csv", index=False)
product_df

,Product_ID,Product_Name,Category,Item,Marketplace,URL
0,P1,Sony WH-1000XM5 Wireless Noise-Canceling Headp...,Electronics,Headphones,Amazon,amazon.com/Sony-WH-1000XM5-Headphones-Hands-Fr...
1,P2,Ninja AF101 4-Quart Air Fryer,Kitchen Appliances,Air Fryer,Amazon,https://www.amazon.com/Ninja-Capacity-Dehydrat...
2,P3,"CeraVe Hydrating Facial Cleanser, 16 oz",Beauty,Facial Cleanser,Amazon,https://www.amazon.com/CeraVe-Hydrating-Facial...

In [6]:
from dotenv import load_dotenv
from openai import OpenAI
import os
from pathlib import Path
import pandas as pd

load_dotenv()          # loads OPENAI_API_KEY etc. (we're not using it yet)
client = OpenAI()      # just to confirm imports work

# Load the product list you already created
product_df = pd.read_csv("data/metadata/product_list.csv")
product_df

,Product_ID,Product_Name,Category,Item,Marketplace,URL
0,P1,Sony WH-1000XM5 Wireless Noise-Canceling Headp...,Electronics,Headphones,Amazon,amazon.com/Sony-WH-1000XM5-Headphones-Hands-Fr...
1,P2,Ninja AF101 4-Quart Air Fryer,Kitchen Appliances,Air Fryer,Amazon,https://www.amazon.com/Ninja-Capacity-Dehydrat...
2,P3,"CeraVe Hydrating Facial Cleanser, 16 oz",Beauty,Facial Cleanser,Amazon,https://www.amazon.com/CeraVe-Hydrating-Facial...

#Product 1 details

In [7]:
# Make sure the raw folder exists
raw_dir = Path("data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)

# === PRODUCT 1 DESCRIPTION (Sony WH-1000XM5) ===
p1_description = """
- Sony WH-1000XM5 Premium Noise Canceling Headphones, Auto NC Optimizer, 30-Hour Battery, Alexa Voice Control, Midnight Blue
- NOISE CANCELLATION: Immerse yourself in the world of music with these noise cancelling headphones, the Sony WH-1000XM5. They come equipped with an advanced noise cancellation feature, powered by two processors controlling eight microphones. Experience the magic of noise cancelling headphones bluetooth technology, ensuring an uninterrupted listening experience free from external disturbances. This unique, distraction-free listening experience sets the Sony WH-1000XM5 apart from other headphones in the market.
- HANDS-FREE CALLING: Step into the future of communication with the Sony WH-1000XM5, a pair of over-ear headphones that make crystal clear hands-free calling a reality. They come equipped with four beamforming microphones and advanced audio signal processing. These over ear headphones ensure your voice is heard clearly, even in noisy environments. This feature is a boon for professionals and individuals who value clear, crisp communication.
- LONG BATTERY LIFE: Say goodbye to battery anxiety with the Sony WH-1000XM5, a wireless headset that offers up to 30 hours of playback time on a single charge. These head phones also feature a quick charging option that provides 3 hours of playback with just a 3-minute charge, ensuring uninterrupted music enjoyment. (USB Type-C Cable included)
- COMFORT & STYLE: Experience the perfect blend of comfort and style with the Sony WH-1000XM5's lightweight design and soft fit leather. These headphones are designed for maximum comfort, allowing you to wear them for extended periods without any discomfort. Sound quality and comfort go hand in hand with these headphones, making them an ideal choice for music lovers.
- TOUCH CONTROLS: Take control of your music with the Sony WH-1000XM5's intuitive touch controls. With a simple touch, you can pause, play, skip tracks, control volume, activate your voice assistant, and answer phone calls. This feature makes the Sony WH-1000XM5 a must-have for those who value convenience and control.
"""
print(p1_description[:200])

- Sony WH-1000XM5 Premium Noise Canceling Headphones, Auto NC Optimizer, 30-Hour Battery, Alexa Voice Control, Midnight Blue
- NOISE CANCELLATION: Immerse yourself in the world of music with these no

In [25]:
# === PRODUCT 1 REVIEWS (Sony WH-1000XM5) ===
p1_reviews = [
    """I think I'm more than a little red-faced right now, because I sorta (sorta???) jumped the gun on rant from a day or so earlier (ya think?). Turns out that my XM5 DOES have a fairly simple reset process that Sony Customer Service was kind enough to send the directions to me via email. And best of all it really worked, so the noise canceling function is back up and running again, apparently as good as before. I also found out that my headphones still were under warranty (1 year warranty coverage), so if the reset had failed I would still have about two months to get the unit back to Sony for repair or replacement. Big oops.

I sincerely apologize to any Amazon customers for my indignant and hasty tirade where I threw Sony under the proverbial bus. That was very much premature on my part and I deeply apologize to all of you who rely upon these reviews for accurate and unbiased user opinions on the products that you're interested in buying. But most of all I want to apologize to Sony, because I think my rant hurt them the most. Given how well their customer service people responded and sought to take care of my problem with my XM5, I certainly truly do deserve to eat a big slice of humble pie.

Revised rating: 4.5 stars instead of the original 5-star rating, because a printed owner's guide wasn't included in the original XM5 packaging.]

[The Update: Well it was an extremely good 10 months. Up until today I had few if any serious complaints about the XM5. But today things are different because the noise canceling function decided to, well you know, "S" the bed. Basically the failure seems to be with the NC function button, which no longer allows me to switch the noise canceling on or off. And unfortunately for me the XM5's NC is in the OFF setting. But I think there's likely something that's a deeper problem with the NC circuitry because the auto-mute function is "working" (well at least it's making the on/off sound effects as if it's trying to work) even though it's definitely NOT in noise canceling operation. I guess this is one of those times that I wish I had opted for the Amazon extended warranty. But I didn't so that's that.

Less than a year of perfectly functioning use; a bloody shame, this. What once was a product that I gave a five-star rating, but with a very key component feature now non-functioning, it's most sadly a less than one-star headset from this point going forward. Yes it still works for simple listening, whether to music or a phone call, but it's the NOISE CANCELING that made it completely worth the $300 cost (after tax) for me. And now that's dead and gone.

Naturally failure is never an option that's desired and I do know that "S" happens, but I can't help but feel that this time Sony has let me down given the relatively short amount of time that this headphone has been in non-daily use since both my now ancient XM2 and dusty XM3 are still working as if they were just taken out of the box. Yeah...I'm definitely NOT happy, and not particularly inclined to take a chance with the newer XM6 that's now live. I think Sony may have just lost me as a customer, but maybe a calmer head will prevail but the way I'm feeling right now, I sorta doubt it.]

My original review:

I recently bought this XM5 as a perceived upgrade from my old XM3 bluetooth cans. I had held off this purchase, thinking that by now Sony would've released the XM6 by now. But no, Sony decided to continue making and selling the XM5. Tired of any further waiting for something that might not happen anytime soon, I finally caved and bought the XM5 when Amazon put the price back under $300 for the October 2024 Amazon Days.

The first thing I noted was how CHEAP the packaging and the accompanying accessories were for this XM5. No stout carrying/storage case this time around. The headphone's boxed packaging might appear to be about Sony trying to be environmentally conscious and being "green", but I suspect that Sony was more about SAVING some green by cheapening up their packaging costs. Even at a discount price, the rudimentary unboxing process made me feel a bit cheated.

However after charging up the XM5, I have to admit that in the end it's really only about the user experience with the headphones. And I must confess that it's pretty great, a definite step forward from the XM3 from two generations before. The XM5 is definitely more comfortable for me than the XM3, which itself wasn't all that bad to begin with. I still loathe the swipe controls on the right earpad, but at least I god used to them during my years of using the XM3.

I have six plus decade old ears, so a LOT of the sonic range is now denied to my brain as my ears certainly don't perform like they used to. But I still can hear enough to say that acoustically the XM5 is a noticeable step forward from the old XM3. While initially the XM5 sound seemed a little colder and a bit on the sharp side, the soundstage imaging is better and more appealing to me, and detail recreation seems marginally improved over the older headphones. So far well-recorded live performances sound a bit more spatially realistic than what was possible with the XM3, and as the burn-in hours add up (roughly about 120 hours of burn-in so far), I suspect that these nuances with further blend, warm up and smooth out.

I don't generally use over-ear wireless headphones for phone calls, so I can't really comment about this feature set of the XM5 when I used it with my cellphone. It does seem to work okay, and persons on the other end seem to regularly claim that they can hear me well enough.

All in all I'm pleased with the XM5 so far. It sounds nicer than the retiring XM3 I had been using, and it fits my large noggin decently well. I do think that the headband is, if anything, a bit on the loose side. But that does seem to aid in making the XM5 wear as comfortably as it does for me. The XM3 was a difficult set to wear to sleep; any slight turn of my head at night often resulted in neck pain the next morning. I've not had this problem at all with the XM5. So far it's been a 5-star experience, and I'm looking forward to continuing to use these for the next few years.""",
    """I really liked this product, but I did not like the color. I thought the color would be more of a true Mauve but it's really a white-grey pink. I think it's worth the money if you get it on sale.
Bluetooth connect connectivity was really great but I did notice that whenever I got on a social media app say like TikTok or Instagram there would be a good 2 to 3 second delay before it would catch on. So if your music was playing it would delay for 2 to 3 seconds and then catch on that you're on social media likewise, if you switch from social media app to your music again there was a delay as well. I didn't get to try it with like movies or Netflix or YouTube so I can't speak for that, I also only kept them for about one day.
It was really easy to use downloading the app was quick and easy, to download I would say that setting up everything you need or like setting up the equalizer is easy but you need a little bit of time and patience. You're gonna need at least 10-15 minutes to do that.

Another thing I would say is that the sound quality out of the box does not compare to my AirPod Pro 2, I found that it was lacking in base and treble, I have a feeling that if you liked watching or listening to podcasts, that sound profile would be really good for you. It was just bleh out of the box, but once I use the equalizer and I was able to customize it to my preferences, it worked great. Again I think the product is good. I just returned it because I realized I wanted the XM6 instead. Also, I didn't get a chance to try it with phone calls either so I can't speak on that.""",
    """I thoroughly enjoy what Sony has to offer in their product line. I have the PlayStation 5, a Sony Bravia 4K TV and several other Sony products. Yes although I have owned a few of their product line I will not try to be biased here with the review. What got me into Sony products was really their earphones dating back to 2011! They have the best earphones you could get for $20 back at the time in 2011 and now the quality they still continue to put out never disappoints! Here's the pros and cons of the Sony WH-1000XM5.

Update: I also picked up the XM4 Earbuds from Sony and take note that those are on a different level for listening to music compared to the XM5 Over the Ear headphones. Shares the same features like the XM5, not the same sound like over the ear obviously but also more marketed to those who goes to the gym and likes something more compact.

Pros:

Comfortable and lightweight!
I don't ever have a complaint with what they have to offer when it comes to comfort. These are better than BOSE in regards as to comfort. I think the one thing that makes them comfortable also is that they are light. They weigh only about 0.56 pounds! People tend to have problems with headphones if they are heavy in my opinion! I also assume they use a low density memory foam for cushioning which is great but will eventually need to be replaced or tended to if left compressed or squished for too long.

Unique features
Noise Cancelling is top notch but not much different than their previous lines in my opinion! It is a standard these days to get noise cancelling and the headphones are great for drowning out noise if need be. They also tend to those who need to be aware of their surroundings by implementing a ambient mode like previous models. Works great and works like a charm by either taking the headphones off or covering the touch control panel. Also the Speak to Pause Music feature is insanely nice to have! Helps when your hands are busy and or you just don't want to adjust your headphones having to speak.

Superb sound!
The sound quality out of these are amazing! Does really well in all areas of music genres. Particularly really in low frequencies for bass! I get to enjoy these at a great volume and it pairs amazingly with my PS5 as a gaming headset! (Will mention the headphones does not come with a microphone for gaming when using a headphone jack.) As a pair of noise cancelling headphones, you can expect to hear a positively good detail in music, movies, gaming or even a phone call! They are clear and surprisingly really balanced. The microphone on these headphones for phone calls are great. Better than the previous versions.

Fast charging!
The charging rate of these headphones is incredible! I never knew how fast charging can be with this! There's times I have left this powered on overnight as I'm at work for my 10 hour job and it was drained by the time I wanted to use it again. In those times I left it charging and goodness greatness these were ready to go in a about 10-15 minutes! I enjoy these so much that I'm actually glad they have a 24-30 hour battery life.

Cons:

Cost.
Its expensive! If you can get these on sale, it's worthwhile! If it's in your budget go for it! You pay for what you get in my opinion and these are worth their weight in gold!

Fitment.
They don't exactly fit around my short wide neck whenever I need to take it off and be present in a conversation or in my surroundings. Not exactly a big matter or deal breaker. More so it's a personal perspective. My neck size is 15 ¾ inches in circumference and that's pretty average I believe. I have to extend these in order to keep them around my neck without compromise. They also do not fold inward like the previous Sony headphone models but again never a issue.

Cushion. Yes the ear cup cushions are comfortable but again when I place them around my neck it compresses the cushion to a point where it feels awkward after putting it back on. I'm looking at other options to replace their soft fit leather design.

Update: There is different earcups that you can replace the OEM cups with but it comes at a cost of I believe $60 which is worth noting.

Conclusion.
Worthiness of $350+ (price as of 12/07/2022) during the holidays? Yes!

Personal opinionated review:
Sony WH-1000XM5 or other leading competition? Sony, easily Sony. I've never been unhappy about this purchase and I tell people that Sony is industrial leading company that continues to impress people when it comes to their headphones. Beats by Dre(Apple), Apple and Bose has always been great by popularity but Sony gets appraised by quality!

I will update this review as I go until they put a new model out.""",
    """One of the most frustrating device I've EVER used. I've tested this on 3 separate PC's! If you want to wirelessly connect this to your PC via Bluetooth, hope whatever you're doing is worth stopping! 7 out of 10 times it just connects for a few seconds (no sound), then disconnects, and repeats forever till you LITERALLY RESET YOUR PC and hope it works this time. There's no way around it. I've tried unpairing it from the PC, resetting the headphones, updating the firmware of both devices.

NOT ONLY THESE ISSUES but at COMPLETE random it'll decide to turn on "Speak to Chat" without ANY input or button presses from me. Having this option on means every time you speak, grunt, or hum, it'll drastically turn down the volume of the sound in your headphones for about 5 seconds, forcing you to stay as quiet as possible. The only way to turn this off is to go into the app and turn it off, EVERY time."

I no longer recommend this device. Sure, it works pretty well, but with all it's issues, if I had another choice that was equal, I'd pick something else.

Edit after 5 months of use:

Disconnects are more frequent, and at times it would suddenly lower the audio quality. The only way to fix it is to stop everything you're doing, turn it off, turn it on, and hope it reconnects. If I could, I'd get a refund. Either I have a defective model or it happens to everyone just not as frequent.

**Edit after a month of use:

Using Multi-device connection is very spotty, 3 out of 10 times the headphones will completely turn off without warning, even with a full battery. Noise cancelling is still very annoying, I'll hear all the sound around me till it decides to kick in and block some of it. With no way to adjust the amount of Noise Cancellation happening, the M3's I've been using has better blocking on some occasions. The issue with the band on the top is still just as bad, it genuinely hurts after long amounts of use. The only improvement from the M3 that I see is I can KIND OF sleep on my side with these on and they stay on my head better without sliding down.

I still do no recommend this unless you plan on wearing it for short periods and in a quiet environment.**

So this review is coming from someone who's worn the M3 Headset for over 4 years and I have to say, it's awful.

I live in a place where there's sound in every direction. Dogs barking, kids screaming, everything you can think of, and ANC is a requirement for getting any work done.

So the good:
- Ear cups are comfortable, doesn't crush your head after long periods of time.
- Sound is good, not absolutely amazing, but good. You need to download the Sony app to alter the sound to allow any bass to work, otherwise it'll sound static-y.
- ANC is awesome but it's adaptive, which I don't like, but can be a plus for some. When it worked it blocked out almost every single sound.
- The case design is cool, it has a little compartment inside that holds the charger cable and headphone jack.

The bad:
- I'm used to my M3's cancelling noise constantly, this device would adapt to the sound around you, letting sound bleed through before blocking it out after. Example: I was listening to a song at moderate volume, I could make any sound I want and I couldn't hear it. When the music had a break in volume, I could hear a LOT outside the headphones.
- The head band that goes over your head is PAINFUL! It legit hurt after only an hour of use, it has almost NO padding and it was a thin plastic.
- THE COLLAPSABLE CASE IS TERRIBLE! I unzipped the case to take the headphones out, I used them for a good 2 hours, put them back into the case, and when I went to open it again the zipper got stuck and it's IMPOSSIBLE to open now. Trust me, I got three separate people to try and open the case, they can't.

I've been looking forward to a new ANC headphone brand, and I'm disappointed Sony didn't have someone wear these for more than an hour or try zipping and unzipping the bag more than a few times before going "yep, let's send them out.".

Sadly, I do no recommend these unless they are on sale and you DIY a comfortable way of wearing them for the top of your head. If they update the ANC and you want to work on making it not hurt the top of your head, they are decent, but not 400$ plus tax decent.

The red circle on the picture shows a hole in the zipper, making it impossible to fully open.""",
    """There's A LOT to love about the Sony WH-1000XM5. I really wanted to write a rave review on them. Unfortunately I've also had a series of horrible problems that make them impossible to recommend.

I'll start with the good. 1) These have the best ANC (active noise cancellation) on the consumer market right now. I also have Airpods Max and have compared with a freind's top of the line Bose QC Ultra. These put both to shame when it comes to ANC. It's incredible. Like so good it's almost dangerous.... I kinda worry I wouldn't hear a fire alarm going off while listening to music with these lol. I should note though, that to get this ANC performance you have to make sure there's nothing between the earpads and your head, like a hat or bunched up hair. My metal framed glasses don't make a difference, but my chunkier plastic frames let a bit more noise through 2) The battery life is amazing. I've been getting 24-28 hours of use with ANC on for each charge. They also charge fast - for me it's typically 45 minutes to go from zero to fully charged. For fast charging you do need a quality USB-C cable (I use Anker cables - they're excellent and very affordable). When I used a cheap crappy cable it took over 2 hours. 3) They're incredibly light-weight and very comfortable. I almost forget I'm wearing them. The ergonomics make them feel like they're custom made for my head and the ear pads and head band are the softest I've ever felt on headphones. The build is pretty plasticky, but they still feel well made / durable... and I think it's worth it for the weight reduction it allows. 4) Like any Bluetooth noise canceling headphones you're not getting hi-fi audio quality, but its better than most other bluetooth headphones. It's not as good as Airpods Max, but better than Bose and any of the cheaper bluetooth headphones I've tried. The most notable weakness is some muddiness in the lower frequencies, in my experience. 5) The case it comes with is awesome. It's a bit bulky, but it keeps the headphones very well protected and has a small compartment that you can keep a charging cable or 3.5mm audio cable in (which you can use for a wired connection if the battery dies, if the device you're using has a headphone jack). It's also very nice aesthetically. Overall the case puts Apple's Airpods Max case to absolute shame - that one barely covers half of the headphones, so it's worthless for protection. I'd honestly throw it away, but Apple is a dick and decided to make it so the headphones are always on and using battery unless you put them in their crappy case. 6) If you download the mobile app, there are tons of options to customize your experience. You can change the EQ, turn speak-to-chat on/off (disables ANC when it detects you're speaking to someone), choose your priority between sound quality vs. stable bluetooth connection, allow to connect to 2 devices simultaneously, integrate Siri or Amazon Alexa, customize controls, and a bunch of other things.

Okay, now the problems. 1) A week after I bought them the speaker in the right ear started randomly making a loud buzzing/popping noise periodically. It's not all the time, but pretty frequent and very annoying. It happens for about 30 seconds a few times every hour of use. Sony claims it happens in places where ultrasonic waves are used to eliminate rodents and suggests you turn off ANC to prevent it... which is aggravating. ANC is the only thing that makes these worth such a high price tag and Sony is the only brand with that problem. Also, I'm 90% sure their explanation doesn't even apply to my environment. 2) Just two weeks after I bought them the touch controls started FREAKING OUT, detecting gestures when I wasn't even touching them. It rapidly flips between playing and pausing my music, skip songs, flip between enabling/disabling voice-to-chat, etc. all on its own, making them entirely unusable when that happens. It happens every hour or two, and once it starts it continues until I turn them off and back on. When I contacted Sony about this, they advised me to just disable gesture controls in the app. That prevents it from pausing or skipping my music, but it does not turn off the pinging sound the headphones make when a a tap/gesture id detected, so you still hear rapid random pinging whenever it decides to bug out. SUPER annoying. 3) 4 weeks after I bought them they just turned off on their own suddenly 10 minutes after I finished charging them to 100% and would not turn back on. I tried a factory reset and they still wouldn't turn on. after repeatedly trying to turn them on, they finally did... for a second, but shut down right after connecting them to my device. I figured they were completely busted, but when I tried again a few hours later they started working again and were fine for a few day... then it happened again. No idea what the deal is, but it's happened 4 times now, so I need to send to Sony to see if they'll fix them. Based on past experience trying to use Sony's warranty for repairs on other products though, they're probably going to send them right back and claim nothing is wrong because it didn't happen during their 30-second inspection.

To summarize, these are SO CLOSE to being the best wireless ANC headphones to buy right now IMO. I really love them when they work... whenever I have to use my much more expensive Airpods Max, they make me wish I were using the XM5s minus all the issues. When they work, I prefer almost everything about the XM5 over the airpods. Unfortunately they're ruined by a few really bad problems. I would recommend getting the WH-1000XM4 instead. They have the same noise cancelling performance and most of the other great qualities and haven't been plagued with bugs. They're slightly less comfortable, but the tighter fit makes them more secure, which can be a benefit for people who want to wear them while working out.""",
"""I previously owned the older version of these Sony headphones and absolutely loved them. Unfortunately, I lost them during a trip, so I decided to invest in the newer WH-1000XM5 model — and it did not disappoint!

This version is a clear improvement in both design and performance. The noise canceling is simply outstanding — it completely blocks out airplane noise, chatter, and other background sounds, making traveling so much more relaxing. The sound quality is top-notch: clear highs, deep bass, and perfectly balanced tones.

I mainly use these headphones during flights, and they make a huge difference. The lightweight design and soft ear cushions make them extremely comfortable to wear for long periods. The battery life is excellent, lasting through multiple flights on a single charge, and the auto noise-canceling optimizer works flawlessly in different environments.

The only downside is that this model doesn’t fold like the previous version, which makes it a bit less compact when packing for travel. However, the carrying case is well-designed and protective, so it’s not a major issue.

Overall, this is a premium product that truly delivers what it promises. Sony continues to set the standard for noise-canceling headphones. If you travel often or simply want the best possible audio experience, the WH-1000XM5 is absolutely worth it.""",
"""I recently picked up the Sony WH-1000XM5 headphones, and while they come with a lot of hype, I must say my experience has been underwhelming in many ways. Here’s my honest take:

Build Quality and Comfort:

The first thing I noticed was the flimsy plastic build. Despite being marketed as a high-end product, the Sony WH-1000XM5 feels anything but luxurious. The plastic feels cheap and flimsy, and the overall design looks bulky, which doesn’t match the sleek aesthetic I was expecting. The earcups are tight on my ears, and within 40 minutes of wearing them, I start feeling the discomfort and heat building up. They’re simply not as comfortable as they should be for headphones at this price point.

Phone Calls:

Using these for phone calls has been a frustrating experience. Even after disabling active noise cancellation, I still struggle with mute issues and can’t hear my own voice clearly. This results in me unintentionally raising my voice, which not only makes the conversation awkward but also strains my throat. To manage this, I’ve had to slightly shift the headphones off my ears, which isn’t ideal.

Sound Quality:

I’ve been using the Sony WH-1000XM5 with my iPhone, and despite the support for LDAC, I wasn’t able to fully take advantage of its high-resolution audio because my iPhone doesn’t support LDAC. And even if I did have LDAC-compatible devices at home, the need for special hardware to support it makes it feel like a limited feature. For standard audio, the sound quality isn’t a huge improvement over my older Dr. Dre Beats headphones, which I bought back in 2017. There’s nothing that truly blows me away, and the difference isn’t as noticeable as I hoped.

360 Reality Audio:

As for 360 Reality Audio, it’s not compatible with the music I already have in my library. To make use of this feature, I would need a premium subscription to services like Tidal or Deezer, which adds an extra cost. Unlike Apple headphones, which allow spatial audio with music already stored on my iPhone, Sony’s approach feels restrictive and less convenient.

Application and Functionality:

The Sony Headphones Connect app is nothing special to me. The notifications about random things, like “what time of the day it is”, feel unnecessary and annoying. Additionally, the auto-pause feature (music stops when you remove the headphones) and auto-shutoff after a period of inactivity seem more like gimmicks than practical features. These aren’t exclusive to the Sony headphones and are available on most modern headphones. They’re not a unique selling point.

USB-C Issue:

One of the most disappointing aspects of these headphones is the lack of USB-C support for audio. This limits the versatility of the headphones and prevents you from taking full advantage of their audio capabilities, especially when using them with other devices. It feels like a missed opportunity for better compatibility and sound quality.

Final Thoughts:

Overall, the Sony WH-1000XM5 headphones don’t live up to the premium expectations. They feel uncomfortable, the sound quality isn’t revolutionary, and 360 Reality Audio and LDAC features seem underutilized for someone who uses standard devices like the iPhone. For the price, I expected more comfort and a noticeable sound upgrade compared to my older headphones, but sadly, they haven’t delivered. The application notifications and unimpressive auto features further detract from the experience. At this price point, I’d recommend looking into other options if you’re truly seeking audiophile-quality sound and comfort.""",
"""I had the WH-1000XM3 for a long time, until one tired morning while getting gasoline after a busy night shift, I must have put it on top of the gas pump and left it there. I didn't want to spend $350 for the WH-1000XM5, but I chose it over the Bose because I knew the Sony will last.

I was decently happy using the XM5 for about a year. I thought the quality was similar to the XM3 in sound quality and build. Sony ships these with a one year warranty, and it's unfortunate the issues and concerns didn't come to light a year after purchase.

1) The biggest issue is that two or three times a day (with maybe one to six hours of use/day), the headphones suddenly loose power. The headphones normally create audible beeps for connecting and disconnecting bluetooth, as well as for powering up and down. When this sudden loss of power happens, all music stops, and it goes silent without any beeps. Tapping on the headphone to adjust the volume or fast forward does nothing. All things point to power being lost, as if the battery disconnected.

There is a feature called "Automatic Power Off" that turns off the headphones when the headphones are removed, but even with this feature disabled, the power loss issue still happens.

This didn't start until about nine months ago, so I've been hoping that some firmware update will fix the issue. It's a very frustrating issue, and this really makes me question about the quality of Sony products now. I feel like $350 headphones should have a warranty period longer than a year.

2) The headphones start twisting on my head. Because of the way the swivels are designed, after a short while, the headphones start to twist around on my head. I tried my best to simulate how it looks on my head in the picture with the headphones on the pillow. The XM5 turns the ear cups toward the same side 90 degrees to make the headphones flat. I actually haven't ever used the case it came with, but this is how it fits in the case.

In comparison, the XM3 ear cups also turn the same direction 90 degrees, but there's an extra swivel that allows one ear cup to be inside and the other outside. It's a bit hard to explain, so go to Sony's site and look for the photo. Maybe because of the design of the XM5 swivels is why it becomes crooked on the head after a while. It really doesn't affect function, but it just looks really silly.

3) Not really an issue with the XM5, but have you ever tried the Apple AirPods Max? They are $250 more and for some reason, I find them unnecessarily heavy, but they produce sounds so much better than the XM5.

I wish I could return these.""",
"""First of all I will start out saying these are very comfortable, and the sound quality is excellent with Bluetooth when functioning.

Battery life is satisfactory the first month of use, although I hear the battery is not replaceable.

Noise reduction - works very well. At times, I have a rack of noisy dell servers in my work area - and with the headphones on I can't hear them at all.

My usage model may not be what is expected from Sony, so let's go over that first.

Primarily, I use these on a windows PC, a Mac, an iPad or iPhone - for music, AV conferencing, video such as YouTube - and gaming.

And so, from a usability perspective, there are some further considerations

First off, out of the box the headphones have particular settings for power on timeout, audio configuration and ANR feature, that are required to be accessed by the user - and these settings while extremely important - *they are NOT available from the headphones or a PC*, *instead, they are only available from android or iOS devices*.

- Out-of-the-Box, the firmware requires an update as some important bugs have been fixed. The update process while working takes *close to an hour* to download the latest firmware due to the speed of Bluetooth. Once the update was complete, the features that are present in the out-of-box version that are not desirable still exist in the updated 1.1.1 version;
- No customer documentation shows what features were fixed or enhanced.
- Discovering what version your headphones currently have is also not obvious. It's hidden in the iOS app so you have to spend a few minutes going through all the menus.
- The iOS app is also trying to sign you up, mine user information, and sell you things, so it's fairly annoying to have that built into the app that is meant for basic headphone settings.

- Headphones will occasionally stop receiving audio from the player device for no obvious reason. This falls into several different types of errors. 1) Random turn off (not power or user interaction related, and not related to "keep on while wearing" setting, _OR_ (2) no sound is output for headphones even though PC shows connected, the player is playing. _OR_ (3) PC shows no Bluetooth device on occasion. _OR_ (4) video/audio player on the PC will go to a "paused" state. - Keep in mind, no interaction by the user was made with the headphones.
- In the case the headphones randomly power off, then just turning them back on, and pressing the left button a couple times will restore. It takes about 10-20 seconds to get back to working for the stack to re-establish the connection..
- In the case of random pauses of your YouTube player. Using a tap on the right side will restore play, Sometimes many hours will go by without this problem, but at other times this will happen multiple times in a just a few minutes. But it gets better! Sometimes using a tap to start playing again, will start a similar player on the iOS device - even though you never switched from using the PC by any user action.
- Using the headphones in a game environment seems to increase the occurrence of these sorts of issues. Having a YouTube player open, but in a pause state while having a game open and audio from the game playing to headphones will complicate matters. Occasionally the sound will stop working here, and tapping the right ear piece in the game will start the YouTube player, but not connect you to the game sound, and sometimes the game sound starts working, and other times you get a mix of both.
- Sound delay from sound being played on PC to the time it's actually heard on the headphones is quite noticeable at times and not a fixed but slowly varying quantity. I would estimate as much as 200ms at times.
- On occasion the headphones will switch some internal operating mode and then raise or lower the volume of the playback by as much as 40% or so. Completely with no user interaction. This problem does not seem to happen often and seems somehow related to the ANR mode.""",
"""Nicely designed and has a quality feel to it. My Bose QC35 headphones finally died after 7 years and I was looking for a replacement. I was going to replace with the new Bose Ultra but these were on special price for Prime Days and wanted to give them a try. So far I’ve been extremely happy with them. I use mine daily for Teams calls, listening to music and streaming services. Sound quality is excellent with music and movies as is call quality. Gesture controls are a nice feature. I have mine set to ANC all the time. I’m not a fan of the ambient noise feature or the auto change. The app features and ability to adjust the EQ are nice to have. I have a less expensive pair from Sony that I was using at the office for teams meetings and was not very happy with the ANC. There is a huge difference in the ANC experience as well as overall quality fit and feel with this higher-end headphone versus Sony‘s lower-end."""
]

len(p1_reviews)

10

In [27]:

# Save Product 1 description as a text file
p1_desc_path = raw_dir / "product1_description.txt"
p1_desc_path.write_text(p1_description, encoding="utf-8")

# Save Product 1 reviews as a CSV
p1_reviews_df = pd.DataFrame({
    "product_id": ["P1"] * len(p1_reviews),
    "review_text": p1_reviews,
})
p1_reviews_path = raw_dir / "product1_reviews.csv"
p1_reviews_df.to_csv(p1_reviews_path, index=False)

p1_desc_path, p1_reviews_path

(PosixPath('data/raw/product1_description.txt'),
 PosixPath('data/raw/product1_reviews.csv'))

In [29]:
print("Description preview:\n", p1_desc_path.read_text(encoding="utf-8")[:300], "...\n")
print("Reviews preview:")
p1_reviews_df

Description preview:

- Sony WH-1000XM5 Premium Noise Canceling Headphones, Auto NC Optimizer, 30-Hour Battery, Alexa Voice Control, Midnight Blue
- NOISE CANCELLATION: Immerse yourself in the world of music with these noise cancelling headphones, the Sony WH-1000XM5. They come equipped with an advanced noise cancellati ...

Reviews preview:

  product_id                                        review_text
0         P1  I think I'm more than a little red-faced right...
1         P1  I really liked this product, but I did not lik...
2         P1  I thoroughly enjoy what Sony has to offer in t...
3         P1  One of the most frustrating device I've EVER u...
4         P1  There's A LOT to love about the Sony WH-1000XM...
5         P1  I previously owned the older version of these ...
6         P1  I recently picked up the Sony WH-1000XM5 headp...
7         P1  I had the WH-1000XM3 for a long time, until on...
8         P1  First of all I will start out saying these are...
9         P1  Nicely designed and has a quality feel to it. ...

#Product 2 details

In [30]:
product_df = pd.read_csv("data/metadata/product_list.csv")
p2 = product_df[product_df["Product_ID"] == "P2"].iloc[0]
p2

Product_ID                                                     P2
Product_Name                        Ninja AF101 4-Quart Air Fryer
Category                                       Kitchen Appliances
Item                                                    Air Fryer
Marketplace                                                Amazon
URL             https://www.amazon.com/Ninja-Capacity-Dehydrat...
Name: 1, dtype: object

In [31]:
raw_dir = Path("data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)

# === PRODUCT 2 DESCRIPTION (Ninja AF101 Air Fryer) ===
p2_description = """
- Ninja | Air Fryer | 6.5 QT Pro XL Capacity fits 9lbs of Wings | 6-in-1 Max Crisp, Air Fry, Roast, Bake, Reheat & Dehydrate | Nonstick Basket, Crisper Plate & Recipe Guide | Grey | AF181
- MAX CRISP TECHNOLOGY: Delivers up to 450°F of superheated air for faster, hotter, and extra-crispy results using little to no oil—perfect for fries, wings, and more. Achieve that golden crunch with rapid air circulation. ​
- Guilt-Free, Healthy Fried Foods: Enjoy the indulgence of fried food with up to 75% less fat compared to traditional deep frying. Tested against hand-cut, deep-fried French fries for proven healthier results.
- XL Capacity Air Fryer: The 6.5-quart nonstick basket and crisper plate hold up to 5 lbs. of French fries or 9 lbs. of chicken wings ideal for family meals, game day, and meal prepping.
- Cooks Frozen Foods Fast: Go from frozen to crispy in minutes with powerful Max Crisp settings no need to thaw. Get a restaurant-style finish straight from the freezer.
- 6-in-1 Cooking Functions: Includes Max Crisp, Air Fry, Air Roast, Bake, Reheat, and Dehydrate a complete countertop solution for healthier, oil-free meals.
- Space-Saving Design: The compact footprint of the Ninja AF181 fits seamlessly on your countertop without sacrificing its generous capacity ideal for smaller kitchens.
- Easy to Clean: Both the air fryer basket and crisper plate are nonstick and dishwasher safe for effortless cleanup after every meal.
- What’s Included: The Ninja AF181 Air Fryer, 6.5-qt. nonstick basket, crisper plate, a 20-recipe chef-created cookbook, and detailed cooking charts to get you started.
"""
print(p2_description[:200])

- Ninja | Air Fryer | 6.5 QT Pro XL Capacity fits 9lbs of Wings | 6-in-1 Max Crisp, Air Fry, Roast, Bake, Reheat & Dehydrate | Nonstick Basket, Crisper Plate & Recipe Guide | Grey | AF181
- MAX CRISP

In [33]:
# === PRODUCT 2 REVIEWS (Ninja AF101 Air Fryer) ===
p2_reviews = [
    """Been having this fryer for 2 weeks now and it has NOT rested yet. I LOVE IT & wonder how I've gone this long w/out one. Before I start bragging on this thing, I am by no way endorsed by Ninja or getting paid by them. I've owned a few Ninja products blenders and still have one that's over 10 years old. They make quality machines. This fryer is a life & time saver...especially if you're a lazy cook. I have been researching air fryers for the past few months and nothing comes close to the Ninja. The basket size isn't the large 5+ quart capacity like the bigger fryers, (Ninja is only 4qt), but this thing cooks so fast you won't miss the extra 1 qt. It comes w/ a crisper that works perfectly, a recipe book and a multi-layer rack. The first night I had it I made wings and I tell you that I will NEVER buy fried chicken again!!! Yes, they were that crispy and tasted much better. I bought the Louisiana fried chicken flour from Walmart, battered the wings, spritzed w/ a little olive oil and had fried chicken in 10 minutes. No greasy mess, no 3rd degree burns from hot oil, and your house doesn't smell like a chicken joint for 4 days afterward. Because the Ninja uses a ceramic coating on their fryers the clean up is very easy. Next, I made sweet potato fries! Had a bag of frozen ones in the freezer and popped those babies in for 10 min. They were crispier than McDonald's. I tried homemade fries but the procedure takes too long. You have to peel, slice, soak potatoes, dry them...I'm just ready to pop them in the fryer and eat! It has been nonstop air fryer cooking in this house! I hit youtube to get a few recipes and it's been on ever since. What I like best about this fryer is it has a dehydrator feature and how fast it cooks. Frozen chicken wings? No problem! Throw them in the fryer for 10 minutes and they're defrosted. I've cooked pizza, fries, wings, reheated food, fried zucchini, and tonight I baked a chocolate cake. Everything came out perfect! Next up is donuts! The only thing I don't like about this fryer is 30 seconds after it finishes cooking it shuts off. I know this is a safety feature but I always have more items to cook. In 2 weeks, I have used my microwave twice, and that was to reheat coffee. Before I forget, I did cinnamon rolls too! I used the canned Pillsbury ones and it normally takes 20 min in the oven. In the Ninja? 8 minutes and that's if you like them brown. I actually could have stopped it at 5 min and they would be perfect. My house smelled like a Cinnabon factory!😛 I have used every feature on this fryer except the dehydrator but I'll be making beef jerky soon. Overall, I am VERY pleased! The best selling feature was the price & the size. The Ninja is much slimmer than some of the bulkier fryers and fits under my cabinet nicely. I'm also happy it only used 1500W unlike some of the larger fryers that burn 1800 which could kill your light bill. The outside of the fryer doesn't get hot so you won't have to worry about getting burned but do take caution when taking your food out. Is it loud? My exhaust fan on my stove is louder than the Ninja. The extension cord on it is long so you don't have to worry about being limited on where you can place it. I think I've covered everything? This thing is THE BOMB! If you're wondering what cookware you can use, just about anything you place in a microwave you can put in the Ninja. I went to the Dollar Tree and bought a few 7" foil pans I use to reheat food & bake in. Also, grab you some silicone tongs while you're there so you don't scratch the surface of your fryer. This thing has been almost as good as a kid getting a new bike for Christmas. You will NOT be disappointed w/ this purchase. Happy & healthy cooking!""",
    """Wow, this thing is great. So, we finally broke down and got an air fryer. I read the reviews and for the money this Ninja one looked like the best deal. Let me tell you something this thing is great. So, it cooks faster than an oven but probably slower than deep frying. It produces crisp, good tasting food that is almost as good as fried.
As a fatty I got to say I love my fried food. The air fryer tastes much better than baked and better for you than fried. I mean I can tell a difference now, don’t get me wrong. It is not going to taste like French fries deep fried in lard, but its close.
I decide I am going to make hot wings. Good idea, right? Well the first batch came out great. Even better than fried because they were a bit crispier. So, I decide I want to have a glass of wine while I cooked. This was my first mistake. God, I wished I had just went with whiskey. So, I insert the corkscrew into the cork and pop, it broke. Oh well, I thought let’s see what the internet has to offer on alternative methods of wine bottle opening.
The first option is to screw a screw into the cork then pry it out using the screw as a lever. Well, I can’t do that because the corkscrew is broken off into the cork. The second option said to use a lighter to heat but the air in the neck of the bottle and the cork will rise out. The third option was to place the bottle in a shoe to not break the glass. Then smack the shoe against a wall. I went with option two. Note this was my second mistake.
So, I break out the old lighter and start heating the glass up. Mind you I am also flipping my chicken wings in the air fryer while starting to heat up some hot sauce and other ingredients on the stove for my buffalo sauce. I decided I needed help so enlisted my 18-year child to hold the lighter up to the glass while I cooked. No good, this trick isn’t working.
I tell him he can stop we are going to go with option three, the shoe. Here comes the third mistake. I grabbed the bottle. Yep you read that right I bare handed the bottle that I had ben applying a direct flame to for over 5 minutes. To top it off I grabbed the neck. This resulted in the most pain I have ever felt in my entire life. This is the pain Atreyu felt when Artax sunk in the swamp of sadness. This was the pain worse than 10 kicks to the balls. This was real pain. Kidney stones have nothing on my hand at this moment. I was done. My hand felt like it had melted to the bottle.
Remember my son that I had help me? Well he is still there, and I must look like a man so I can’t cry, but boy did I want to cry. I haven’t wanted to cry this bad sense I watched “Ole yeller”. Despite the pain and fighting back tears. I managed to place the bottle in my shoe and set it on the table. I am still wanted to try that trick.
I then went into first aid mode, hand in the sink water running, ahhhh sweet relief. Unfortunately, that was not to last. The cool water only did so much. I decided burn creme would work. Nope don’t have any. Back to the water. Perhaps some ice. Ahhh flip the wings, run the water, check the sauce wait ….
The pot isn’t simmering. Why is the cutting board on the stove look funny? Yep mistake four here I come. I turned on the wrong burner and now my plastic cutting board has turned to liquid on my stove. Hand back in water again. I then retrieve my putty knife to scrape the stove clean. This causes wisps of plastic string to go from the stove to the sink. Hand goes back into the water.
At some point my son decides to wake the wife. Did I mention this was at about 1 am? She come into the kitchen and sees me. With one shoe one, a bottle of wine on the table inserted into my shoe. Note she mentions that is the shoe I walk into bathrooms in and its on her table. She then notices the burnt cutting board and an abundance of melted plastic in the sink. She then simply asks “hot wings hu?”
She is a god wife and wants me to go to the hospital for my possible 3rd degree burns on my hand but me, being a man, I decide I can tuff it out. She ends up getting me more ice and leaving my son in charge to go back to bed once she understands I am not budging on the whole doctor thing.
Anyway, in conclusion the hot wings were the best I have ever made. Although eating them one handed was a bit of a chore. I stayed up all night in pain and now I am out of ice. I never did open that bottle of wine. Also, that air fryer rocks.""",
    """I thought the Ninja air fryer would live up to its hype. I read the reviews, they all seemed positive, but in the end let me tell you the truth about an air fryer.

First of all, I purchased the 4 quart model, (since it’s only my husband and myself) so I thought a 4 quart model would be perfect.
WRONG.

A 4 quart model only fits 2 chicken wings. (See attached photos)
WHO would bother cooking only 2 chicken wings?
It’s ridiculous, especially since photos show 9 wings fitting into the basket. (False advertising)

For every recipe I tried, I also cooked the same recipe in my oven. To test the flavors and the cooking time, not to mention the ease of clean up.
In every single test, my oven out performed and out cleaned the Ninja air fryer.

Case in point:
Chicken wings.
I cooked an entire tray of wings in my oven using non-stick aluminum foil, that could be easily discarded. (Simple cleanup)
When I cooked the 2 wings in the air fryer it made a greasy mess that took forever to clean.

The air fryer brags about “healthy cooking” yet in the Ninja cookbook it states that you MUST use 1 tablespoon of oil and in many recipes they recommend using 3 TABLESPOONS of oil. What’s so healthy about that???

The Ninja air fryer is a con.
Don’t be conned into buying one. You WON’T save time, if anything, you’ll spend MORE time.

And don’t get me started on making French fries in an air fryer. It’s a “babysitting” exercise as you must stop and start the machine every 6 minutes to ensure crispy fries. But first you must soak the fries in water for 30 minutes and then hand dry EACH fry so that there is zero moisture … as if the potato slice has any water at all, it will NOT get crisp. All in all it takes 2 hours to make 1 small batch of French fries. (Peeling, cutting, soaking, drying and then cooking for 25 minutes in the air fryer = Brain Damage)

So much quicker to use a fry pan OR your oven!

In short, I’ll be returning this Ninja and warning everyone I know about the pitfalls of cooking with an air fryer.

PS) I made one more attempt to use the Ninja to cook Brussels sprouts tonight. Followed the recipe yet they totally burnt to a crisp. Now my entire house reeks of burnt cabbage. Yuck!""",
    """I love this air fryer! My previous fryer was a top loader and in order to get the basket out I had to use oven mitts and inevitably I burned myself every time I used it. This one is so easy to load and unload, plus the basket is a lot bigger than I expected.
Two things I liked about my previous fryer over this one:
1. My previous one would preheat. For instance, I could put something in for 10 minutes, push start, and the 10 minutes didn't start until the fryer was preheated.
2. In my other fryer, if I opened it the time would stop, I could flip the food over and close it and push start and the remaining time would restart. With this one I have to either stop the cooking, pull out the basket, flip the food over and then restart (and when I restart its not set at the time I originally set, it reverts back to its own preset so I have to reset the time and temperature).

Overall this one works very well, the food is quite crispy!""",
    """I received this item on 07082025 and was excited to use this. However, when I tried to clean the crisper plate and basket, I could not pull out the crisper plate. It somehow was stuck or wedged in the basket. I tried different ways to pull it out but couldn't. I noticed there were 3 plastic/rubber bumpers on the sides of the round plate which probably caused the plate to be stuck. I tried to use a pair of pliers but covered the handle with a towel so as not to damage the coating. Still would not pull out. I tried to gently twist it and ended up twisting the handle and damaging it which meant it was not moving. I called Amazon customer service and the gentleman was very helpful and said he would send a new air fryer.

I asked him if it was okay to use and test it before I return the product because the replacement was going to take a couple days. He said okay. I tried it on a frozen steak and it worked as described. Just need to adjust the air fryer settings because it was a smaller steak.

When I tried to wash it off, the crisper plate actually came loose and I was able to pull it out. So next time, before I try and forcibly pull it out, I may try air frying something first or placing some oil on the sides and run the air fryer a few minutes to heat it up and try pulling it.

I will wait and see if the replacement unit has the same issue.""",
"""I've only used this air fryer twice, so still very new to air frying.  I've noticed when using it when the time is up and the display says End, the fan is still running.  I shut it down after about 20 seconds so I don't know how long it would have kept running if I hadn't shut it down.  Since I couldn't find anything about this issue in the guide, I called Ninja and was told that although when it says End, the heating element turns off right away, it takes the fan a little longer to stop because it's turning at such a fast rate of speed.  One thing I'm not crazy about is the temperature doesn't stay displayed after you've set it.  Yesterday I set it for 350 and later in the cooking time I wanted to double check the temperature, and to do that I had to push the up or down temp button and when I did that 390 came up!  I think whatever the temperature is set at should constantly be on display.  I did chicken thighs in it and they got nice and crispy and I used a meat thermometer to make sure they were up to 165 and they were quite a bit above that, but when I put the thermometer probe into the meat, blood immediately came out. So I put them back in for another 3 minutes but then I felt the outer part of the meat was overdone.  As I said, I'm new to air frying and I know I have a lot to learn, so hopefully all my concerns eventually get ironed out.  I gave it only 3 stars because I don't know how it's going to work in the long term and I have questions, but it seems very nice and is very easy to clean.
Why did you pick this product vs others?:
I've heard good things about Ninja products.""",
"""Oh my goodness! I just bought this and have cooked two meals so far and the results have been great. I wish I had bought this earlier. This is easy to use, the results are amazing and it is easy to clean-up. My only issue was getting the grill plate out when I first unboxed my new Ninja. You really, really have to tug. Once you do, then it is easier to remove going forward. BTW, 4-quarts is actually a lot. I almost bought a bigger one and then changed my mind. I'm glad I did. I can easily cook a 1-2 lb package of chicken, half a bag of nuggets or tenders, or half a bag of frozen fries/tater tots and have no crowding. If you are single or buying this for just a couple of people, you are probably going to be just fine with a 4-qt model. Frozen french fries took 3 minutes to cook. Chicken tenders took less than 15 minutes to cook. Download the manual on this page and you will be able to see what the cook times are for various items. You can even dehydrate foods with this marvel.""",
"""Too damn noisy. I had a previous version of this basic fryer and was very happy with it. But it died after a short life. Sadly this current, basic incarnation is not making me or my spouse happy. It is fine on dehydrate but when I switched to air fry it sounds like a USAF fighter jet.""",
"""The air fryer cooks as described, but I have experienced a few safety concerns.
My last air fryer, cheaper no-name brand, shut off when the basket was pulled out. The ninja air fryer does not. You must push a pause button before you pull out basket - otherwise it stays on.
I have been burned on both arms- about two inches above my wrist when getting food out of this air fryer. Exact same location on both arms on separate occasions. Never once was burned on other air fryer that I used for over 3 years.
I was excited for what I thought was an upgraded product, but so far have experienced more cons than pros.""",
"""This my first air fryer. I purchased it on sale from Amazon without checking out any ratings of other models. I’ve used it several times a week and am happy with it overall. It browns food better than the oven in much less time, is simple to use, easy to clean and seems well built. There is very little hot plastic odor during use and the outside does not get overly hot. There are two reasons that it’s not 5 star for me. The first reason is that the cord is too short and is only a polarized two prong cord instead of a three prong cord. The main drawback though is that it’s very noisy. This is something that several reviews pointed out but I’m getting used to it."""
]

len(p2_reviews)

10

In [34]:
# Save Product 2 description as text
p2_desc_path = raw_dir / "product2_description.txt"
p2_desc_path.write_text(p2_description, encoding="utf-8")

# Save Product 2 reviews as CSV
p2_reviews_df = pd.DataFrame({
    "product_id": ["P2"] * len(p2_reviews),
    "review_text": p2_reviews,
})
p2_reviews_path = raw_dir / "product2_reviews.csv"
p2_reviews_df.to_csv(p2_reviews_path, index=False)

p2_desc_path, p2_reviews_path

(PosixPath('data/raw/product2_description.txt'),
 PosixPath('data/raw/product2_reviews.csv'))

In [36]:
print("P2 description preview:\n", p2_desc_path.read_text(encoding="utf-8")[:300], "...\n")
print("P2 reviews preview:")
p2_reviews_df

P2 description preview:

- Ninja | Air Fryer | 6.5 QT Pro XL Capacity fits 9lbs of Wings | 6-in-1 Max Crisp, Air Fry, Roast, Bake, Reheat & Dehydrate | Nonstick Basket, Crisper Plate & Recipe Guide | Grey | AF181
- MAX CRISP TECHNOLOGY: Delivers up to 450°F of superheated air for faster, hotter, and extra-crispy results us ...

P2 reviews preview:

  product_id                                        review_text
0         P2  Been having this fryer for 2 weeks now and it ...
1         P2  Wow, this thing is great. So, we finally broke...
2         P2  I thought the Ninja air fryer would live up to...
3         P2  I love this air fryer! My previous fryer was a...
4         P2  I received this item on 07082025 and was excit...
5         P2  I've only used this air fryer twice, so still ...
6         P2  Oh my goodness! I just bought this and have co...
7         P2  Too damn noisy. I had a previous version of th...
8         P2  The air fryer cooks as described, but I have e...
9         P2  This my first air fryer. I purchased it on sal...

#Product 3 details

In [37]:
product_df = pd.read_csv("data/metadata/product_list.csv")
p3 = product_df[product_df["Product_ID"] == "P3"].iloc[0]
p3

Product_ID                                                     P3
Product_Name              CeraVe Hydrating Facial Cleanser, 16 oz
Category                                                   Beauty
Item                                              Facial Cleanser
Marketplace                                                Amazon
URL             https://www.amazon.com/CeraVe-Hydrating-Facial...
Name: 2, dtype: object

In [38]:
raw_dir = Path("data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)

# === PRODUCT 2 DESCRIPTION (Ninja AF101 Air Fryer) ===
p3_description = """
- CeraVe Hydrating Facial Cleanser, Moisturizing Face Wash For Dry Skin, Hyaluronic Acid + Ceramides + Glycerin, Hydrating Cleanser For Normal To Dry Skin, National Eczema Association Certified
- HYDRATING FACE WASH: Daily face wash with hyaluronic acid, ceramides, and glycerin to help hydrate skin without stripping moisture. Removes face makeup, dirt, and excess oil, provides 24-hour hydration and leaves a moisturized, non-greasy feel.
- ECZEMA FACE WASH: Non-foaming cleanser for dry skin with a lotion-like consistency feels smooth as it cleanses, even on sensitive, dry skin. Fragrance-free, paraben-free, non-comedogenic and non-drying. Certified by the National Eczema Association
- MULTI-USE GENTLE CLEANSER: Cream cleanser for face and/or body and can be used as a hand wash. Suitable for daily cleansing morning (AM) and night (PM) for normal to dry skin. Skin care for dry skin.
- 3 ESSENTIAL CERAMIDES: Ceramides are found naturally in the skin and make up 50% of the lipids in the skin barrier. All CeraVe products, formulated with three essential ceramides (1, 3, 6-II)to help maintain the skin’s natural barrier.
- DEVELOPED WITH DERMATOLOGISTS & #1 DERMATOLOGIST RECOMMENDED SKINCARE BRAND: CeraVe Skincare is developed with dermatologists and has products suitable for dry skin, sensitive skin, oily skin, acne-prone, and more.
"""
print(p3_description[:200])

- CeraVe Hydrating Facial Cleanser, Moisturizing Face Wash For Dry Skin, Hyaluronic Acid + Ceramides + Glycerin, Hydrating Cleanser For Normal To Dry Skin, National Eczema Association Certified
- HYD

In [39]:
# === PRODUCT 3 REVIEWS (CeraVe Hydrating Facial Cleanser) ===
p3_reviews = [
    """I wish I known about Cerave long ago in my teens. I had such bad acne, oily skin, and tried so many different products that didn’t work or made it worse. I still had acne (not as bad) into my 30s but after noticing others my age with no acne and at my wits end, I decided to do some research for products that actually worked, not just random products I found in the drugstore skin care aisle but also not break the bank.

After some thorough google research, YouTube reviews, and website reviews, I found Cerave to be a good place to start. I now use Cerave Hydrating Facial Cleanser and rotate out with Cerave’s Renewing SA Cleanser (once a week). I then use Cerave’s Skin Renewing Night Cream (morning and night). I also do hydrating masks once a week, quartz facial rollers from the freezer (morning and night), LED red light therapy every other night, hyaluronic acid serum (morning and night), and Jergen’s Natural Glow Face Mositurizer with SPF 20 (which I will be switching over to Cerava’s tinted sunscreen once my Jergens is gone). I no longer wear foundation because my skin has cleared, my skin tone looks much smoother, and my pores are tighter.

I hope this information might be helpful to others that are struggling with skin care issues like mine. Cerave has, from my experience, provided me with a good quality skincare routine that I’ve been using for over a year now with no issues. I would like to note that I have tried Cerave’s Skin Renewing Retinol Serum that did make me breakout. I discontinued use but after reading reviews, there is a temporary retinol purge period (can last several months) that causes breakouts but is not a permanent side effect. I will probably try this product again because Retinol is suppose to help speed up skin cell turnover and is used to help reduce wrinkles, improves acne scars, hyperpigmentation, and skin tone. It pushes trapped oil and existing clogged pore debris to the surface, which is what causes the breakouts. I’m hoping that since I’ve been on this Cerave journey for over a year that I won’t breakout won’t be as bad this time around. I will update my review after I get through the breakout stage of use.""",
    """I use this product morning and evening and whenever I like to freshen up. Goodbye to using ivory soap bar that after a while dries your face out. I use other products of CeraVe the p.m. and hand moisturizer the facial cleanser works well with a little scrubber that you can purchase separately that really removes all dead cells on face or anywhere else you want to use it. I would give it a five-star if they made a pump that when you get near the bottom you don't have to take the pump out to get the rest of it out for the next couple of days. Also it would be good if you had a clear side window to see how low you were getting. Otherwise this product I've used for about 3 years and works well for me. Price could be a little cheaper but you have to pay a little more for good stuff. I would recommend.""",
    """I gave this CeraVe hydrating facial cleanser 5 stars because it doesn't dry my skin out and it's doing what a good facial cleanser should do, gently clean your face. I recommend this face wash. There are better face washes if you want to spend the money, and you look out and get a product that actually does what it says it does but you'll spend a pretty penny on it. I would do that, because I'm 51 years old and I'd like to continue to take very good care of my skin while aging as gracefully as possible, so this is always my go-to-face wash if I've purchased one or two expensive face washes that misrepresents itself and is harsh on my skin. The face wash I used to use for $65 was wonderful and made skin feel soft and clean without any silicones masking that effect but they discontinued it or change the formulation. So back to good old CeraVe.""",
    """Normally I am a fan of cerave products, but not this one. I accidentally bought it when trying to purchase the cream to foam version. This is actually the second time I've done that, as the products look almost identical but they are not. My husband and I both use and love the cream to foam version, but this one not so much.

Both my husband and I tried to use this, but ended up getting rid of it for different reasons. For my husband, he felt like he had to use a lot of product and it didn't give him that "clean" feeling that the cream to foam version does. For me, it actually caused a pretty intense burning sensation on my face that other cerave products do not. The cream to foam version of this is great for me and does not cause the burning sensation.

Wish they would make the marketing of this product different from the cream to foam one, they are really two completely different products.""",
    """This is just me writing of my personal experience with the product.

First off, I will say that I am not a female, but a thirty-something y.o. male with sensitive skin who has been dealing with acne since my teen years. And I've recently been struggling with a pretty bad breakout which is why I decided to buy this product when it went on sale.

Now, that being said, I cannot understand how this is the bestselling facial cleanser on Amazon.

But anyway... I'll just list my problems with the product.

1. The product does not lather at all, it's more of a cream cleanser, so if you have acne-riddled skin like me, you probably do not want to be rubbing something all over your face; I lightly pat my face with lather when I wash, I do not rub, and this product makes it very difficult to do that.

* Maybe if you're a female it would be good to remove makeup, I don't know, I'm just guessing about that, the creamy consistency and ingredients lead me to think it would, but for me, it serves no purpose as I cannot actually use it to wash my face.

2. It IRRITATES my skin. I've used it three times, and each time it has burned, it's only a slight sting, but it's there.

3. Because of these issues and my desire to not have to return the product, I have tried mixing a small amount of this CeraVe cleanser with a bit of another soap/body wash, I use Olay and/or Dial, hoping it would add the beneficial properties while the soap would ameliorate the negatives, namely, not lathering and being slightly irritating, but unfortunately, the CeraVe seems to basically dissolve the soap and makes the entire mixture extremely thin, with a consistency barely greater than water, so I cannot really use it for anything.

All I can say is, I really wanted to like this product, thought I would based on all the positive reviews and the reputation of the company along with their product pricing, but unfortunately, it doesn't work for me and I'll have to send it back.

Oh, and I give one star for scent because there is no scent, and while some people may think that's a good thing, I like my bath products to have a light/moderate scent.""",
"""I’ve been using this product for months now. I haven’t liked it from day one but the bottle is GIGANTIC and because it’s supposedly a great product, I didn’t want to waste it. What I dislike most is that it doesn’t seem to remove sweat/grease. I get that people don’t want their skin to dry out, but when I go to the gym or hiking, etc, I need to feel like my face is clean afterwards. With this I feel like I am just spreading my own face oil around my face. I have combo skin, so mainly get oily on the forehead and nose. When I’m done washing my face, the forehead and nose still seem greasy, whereas the other areas don’t. I’ve tried using more and rubbing for a while (it doesn’t lather), but it just doesn’t seem like I’m washing my face with anything better than water. It also didn’t help with breakouts, in my opinion, because it doesn’t wash the skin very well. It most certainly doesn’t get make up off, but I don’t know if every face wash is meant to do that. With this, I definitely need to remove my make up first, but for all the people complaining about that, it’s probably because it just doesn’t wash skin, oils, anything else off very well. I still have a ton left. I might use it on days where my skin isn’t very dirty at all. Might throw it away. IDK. Every face wash I’ve tried was better than this.""",
"""I was not trilled with this. I was trying to save money, and when I ran out of my Philosophy Purity I thought I would try this due to review. I just do not like the feel, or the cleaning ability. It has no scent, size was economical, but the pump did not disperse more than a couple of teaspoons per pump. No not easy to use in the shower or tub. I can not state quality because it just did not leave my face feeling clean. This company has great reviews on all lotions creams and even this face cleanser, but it is not the quality I was used to.""",
"""It does not work well. It does not foam. Feels like lotion. My face still has residue after washing. Does not remove my lipstick Maybelline Super Stay. I have to use it twice in the shower just to remove the make up, mascara and eye shadow. The bottle is huge. Not sure why so many great reviews. """,
"""reviMy initial opinion is that it’s a good product. It’s only been in my shower for a week but seems to be cleansing well and not drying out my faceew9""",
"""For years, I associated that "squeaky clean" feeling with a good face wash, not realizing it was just a sign of my skin being stripped of its natural moisture. This CeraVe cleanser has completely changed my perspective. It has a creamy, lotion-like consistency that doesn't foam up, which took a little getting used to. However, it feels very gentle and soothing on my skin and cleanses thoroughly without leaving any tightness or dryness behind. My face just feels soft, calm, and comfortable after using it.

I find it's effective enough to remove daily sunscreen and light makeup on its own. For heavier makeup days, I use it as the second step in a double-cleanse routine and it works perfectly. I appreciate that it's formulated with ingredients like ceramides and hyaluronic acid to support the skin barrier, rather than work against it. It's also completely fragrance-free, which is a big plus for my sensitive skin.

A single bottle lasts for months, as you only need about one pump per wash. It's a simple, no-frills product that has become a reliable and essential part of my skincare routine. It consistently leaves my skin feeling balanced and hydrated.""",
]

len(p3_reviews)

10

In [40]:
# Save Product 3 description as text
p3_desc_path = raw_dir / "product3_description.txt"
p3_desc_path.write_text(p3_description, encoding="utf-8")

# Save Product 3 reviews as CSV
p3_reviews_df = pd.DataFrame({
    "product_id": ["P3"] * len(p3_reviews),
    "review_text": p3_reviews,
})
p3_reviews_path = raw_dir / "product3_reviews.csv"
p3_reviews_df.to_csv(p3_reviews_path, index=False)

p3_desc_path, p3_reviews_path

(PosixPath('data/raw/product3_description.txt'),
 PosixPath('data/raw/product3_reviews.csv'))

In [42]:
print("P3 description preview:\n", p3_desc_path.read_text(encoding="utf-8")[:300], "...\n")
print("P3 reviews preview:")
p3_reviews_df

P3 description preview:

- CeraVe Hydrating Facial Cleanser, Moisturizing Face Wash For Dry Skin, Hyaluronic Acid + Ceramides + Glycerin, Hydrating Cleanser For Normal To Dry Skin, National Eczema Association Certified
- HYDRATING FACE WASH: Daily face wash with hyaluronic acid, ceramides, and glycerin to help hydrate skin ...

P3 reviews preview:

  product_id                                        review_text
0         P3  I wish I known about Cerave long ago in my tee...
1         P3  I use this product morning and evening and whe...
2         P3  I gave this CeraVe hydrating facial cleanser 5...
3         P3  Normally I am a fan of cerave products, but no...
4         P3  This is just me writing of my personal experie...
5         P3  I’ve been using this product for months now. I...
6         P3  I was not trilled with this. I was trying to s...
7         P3  It does not work well. It does not foam. Feels...
8         P3  reviMy initial opinion is that it’s a good pro...
9         P3  For years, I associated that "squeaky clean" f...